### ISSUE TITLE
GH Action and git-secrets not working

### ISSUE THREAD

**Issue by mberrueta** [ruby-kafka-poc/security_api#3]
tested with

          git secret --version
          #  0.4.0 (same pc and server)         
          echo 'gpg --help'
          gpg --help 
          # PC: gpg (GnuPG) 2.3.6 libgcrypt 1.10.1
          # PC: gpg (GnuPG) 2.2.19 libgcrypt 1.8.5

```
      - name: Reveal secrets
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" > ./private_key.gpg
          gpg --batch --yes --pinentry-mode loopback --import private_key.gpg
          git secret reveal -p $PASSPHRASE
```

and

```
      - name: Import GPG key
          id: import_gpg
          uses: crazy-max/ghaction-import-gpg@v4
          with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
```
